name: Build and Test Docker Image

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ai_panel_test -f ./Dockerfile .

      - name: Test Docker container
        run: |
          docker run --rm -d --name test_ai_panel ai_panel_test
          sleep 5
          docker ps | grep test_ai_panel && echo "✅ Dockerfile OK"
          docker stop test_ai_panel


      - name: List published files
        run: docker run --rm --entrypoint ls ai_panel_test /app

